config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
  	resources :gift_wraps
  end
  resources :gift_wraps
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/gift_wrap.rb
class Spree::GiftWrap < ActiveRecord::Base
	belongs_to :line_item

	validates :gift_text, :presence => true

	def self.add_gift_wrap(gift_wrap,line_item)

		wraps = Spree::GiftWrap.where(:line_item => line_item).count
		if wraps < line_item.quantity 
			Spree::GiftWrap.create(:gift_text => gift_wrap, :line_item => line_item,:price => Spree::GiftWrap.price.value.to_f)
			ou = Spree::OrderUpdater.new(line_item.order)
			ou.update_order_total
			ou.order.save
		end
	end

	def remove
		self.destroy
		ou = Spree::OrderUpdater.new(line_item.order)
		ou.update_order_total
		ou.order.save
	end

	def self.price
		price = Spree::Preference.where(:key => "spree_gift_wrap_price").first
		price.present? ? price : 0.00
	end

	def self.total(order)
		gift_total = 0
		order.line_items.each do |i|
			gift_total += Spree::GiftWrap.where(:line_item_id => i.id).sum("price")
		end
		gift_total
	end

end

app/controllers/spree/admin/gift_wraps_controller.rb
class Spree::Admin::GiftWrapsController < Spree::Admin::BaseController

	def index
		@giftwrap = Spree::Preference.where(:key => "spree_gift_wrap_price").first
		if @giftwrap.blank?
			@giftwrap = Spree::Preference.new
			@giftwrap.key = "spree_gift_wrap_price"
			@giftwrap.value = 0.00 
			@giftwrap.save
		end
	end

	def update
		@giftwrap = Spree::Preference.where(:key => "spree_gift_wrap_price").first
		@giftwrap.value = params[:gift_wrap_price]
		@giftwrap.save
		flash[:success] = flash_message_for(@giftwrap, :successfully_updated)
		render :index
	end
end

app/controllers/spree/gift_wraps_controller.rb
class Spree::GiftWrapsController < Spree::StoreController

	def create
		line_item = Spree::LineItem.find(params[:line_item_id])
		Spree::GiftWrap.add_gift_wrap(params[:gift_text],line_item)
		respond_to do |format|
			format.js {
				
			}
		end
	end

	def destroy
		gift = Spree::GiftWrap.find(params[:id])
		gift.remove
		redirect_to cart_path
	end
end

app/helpers/spree/admin/gift_wraps_helper.rb
module Spree::Admin::GiftWrapsHelper
end

app/helpers/spree/gift_wraps_helper.rb
module Spree::GiftWrapsHelper
end

app/views/spree/admin/gift_wraps/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:gift_wrap_options) %>
<% end %>
<%= form_tag admin_gift_wrap_path(@giftwrap), {:method => :put} do  %>
 <div id="preferences" data-hook>
 <fieldset class="general no-border-top">
 		<legend align="center">Set Gift Wrap Pricing</legend>

 


 	  <div class="field">
 	  	<%= label_tag :gift_wrap_price %>
 	  	<%= text_field_tag :gift_wrap_price,@giftwrap.value,:size => 4  %>
 	  </div>
 		<div class="form-buttons filter-actions actions" data-hook="buttons">
        	<button class="icon-refresh button" name="button" type="submit">Save</button>
      </div>
 </fieldset>
 </div>
 <% end %>

app/views/spree/checkout/_delivery.html.erb
<fieldset id='shipping_method' data-hook>
  <legend align="center"><%= Spree.t(:delivery) %></legend>
  <div class="inner" data-hook="shipping_method_inner">
    <div id="methods">
      <%= form.fields_for :shipments do |ship_form| %>

        <div class="shipment">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:package_from) %>
            <strong class="stock-location-name" data-hook="stock-location-name"><%= ship_form.object.stock_location.name %></strong>
          </h3>

          <table class="stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(item.variant) %></td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
                <%= render :partial => "spree/shared/gift_wrap_summary", :locals => {:item => item} %>
              <% end %>
            </tbody>
          </table>

          <h5 class="stock-shipping-method-title"><%= Spree.t(:shipping_method) %></h5>
          <ul class="field radios shipping-methods">
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="shipping-method">
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id, rate.id %>
                  <span class="rate-name"><%= rate.name %></span>
                  <span class="rate-cost"><%= rate.display_cost %></span>
                </label>
              </li>
            <% end %>
          </ul>
        </div>

      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:unshippable_items) %>
          </h3>
          <table class="stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(variant) %>xzszxczc</td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>

    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <%= form.label :special_instructions, Spree.t(:shipping_instructions) %><br />
        <%= form.text_area :special_instructions, :cols => 40, :rows => 7 %>
      </p>
    <% end %>
  </div>
</fieldset>

<br />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), :class => 'continue button primary' %>
</div>

app/views/spree/gift_wraps/create.js.erb
location.reload();

app/views/spree/shared/_add_gift_wrap_links.html.erb
   <% if line_item.quantity > line_item.gift_wraps.count %>
 	<br><br>
 	<div class="gift-wrap cart-form<%= line_item.id %>">
        <a href="#" id="gift_wrap_add" data-id="<%= line_item.id %>">Add Gift Wrap $<%= Spree::GiftWrap.price.value %></a>
     <br>
     <div class="gift-wrap-textarea">
    
     	<%= text_field_tag :gift_text, "",:cols => "50",   :maxlength =>"200", :placeholder => "Enter gift wrap note" %>
     	<input type="button" value="Add" class="add-gift-note" data-url="<%= gift_wraps_path %>" data-line-item-id="<%= line_item.id %>">

     
     </div>
     </div>
  <% end %>	

app/views/spree/shared/_gift_wrap_cart_form.html.erb
<div class="gift-wrap cart-form">
<input name="gift_wrap[add]" id="gift_wrap_add" type="checkbox" value="1">
              Add Gift Wrap<br/> 
               
              <%= text_area_tag :gift_text, "",:cols => "", :rows => "3",:class => "gift-wrap-textarea", :maxlength =>"200", :placeholder => "Enter gift wrap note" %>
</div>

app/views/spree/shared/_gift_wrap_cart_line_items.html.erb
 
  <% line_item.gift_wraps.each do |g| %>
 
  <tr class="line-item">
    <td></td>
    <td>
      <span class="no-link"><b>Gift Wrap:</b></span> "<%= truncate(g.gift_text,:length => 70) %>"
    </td>
<td class="cart-item-price" data-hook="cart_item_price">
    <%= number_to_currency g.price %></td> 
    <td class="cart-item-quantity" data-hook="cart_item_quantity">
<input class="line_item_quantity"   min="1"  size="5" type="number" value="1" readonly>
    </td>
    <td class="cart-item-price" data-hook="cart_item_price"><%= number_to_currency g.price %></td>
    <td><%= link_to image_tag('icons/delete.png'), gift_wrap_path(g), :method => :delete   %></td>
  </tr>
  
  <% end %>

app/views/spree/shared/_gift_wrap_summary.html.erb
<% item.gift_wraps.each do |g| %>
<tr class="stock-item">
                  <td class="item-image"></td>
                  <td class="item-name"><b>Gift Wrap:</b></span> "<%= truncate(g.gift_text,:length => 70) %>"</td>
                  <td class="item-qty">1</td>
                  <td class="item-price"><%= number_to_currency g.price %></td>
                </tr>
 <% end %>